# Generated by Django 2.0.3 on 2018-04-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('base_url', models.CharField(max_length=255, unique=True)),
                ('port', models.IntegerField()),
            ],
        ),
    ]
