# Generated by Django 2.0.3 on 2018-04-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='status',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
