# Generated by Django 2.0.3 on 2018-04-24 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_notebook_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='time2',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='notebook',
            name='time3',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 4, 24, 11, 56, 17, 810947)),
            preserve_default=False,
        ),
    ]
