# Generated by Django 2.0.3 on 2018-04-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180424_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='time3',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
