# Generated by Django 2.0.3 on 2018-04-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180424_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='heartbeat',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notebook',
            name='time2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='time3',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
