# Generated by Django 2.0.3 on 2018-04-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180425_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='lock',
            field=models.BooleanField(default=False),
        ),
    ]
